nggit/tremolo

- setup.py
- tests/http_server.py
- tests/test_http_client.py
- tremolo/__init__.py
- tremolo/__main__.py
- tremolo/asgi_lifespan.py
- tremolo/asgi_server.py
- tremolo/handlers.py
- tremolo/lib/http_protocol.py
- tremolo/tremolo.py
Example:
```python
@app.error(500)
async def exception_handler(**server):
exc = server['exc']
return str(exc)
```
> customizable exception page with @app.error(500)

- alltests.py
- tests/http_server.py
- tests/test_http_client.py
- tremolo/__main__.py
- tremolo/tremolo.py
- tremolo/utils.py
makes sure the server is still manageable under unexpected loads.
> add --limit-memory

- tremolo/__init__.py
- tremolo/asgi_server.py
- tremolo/lib/h1parser/parse_header.py
Before:
```python
REMOTE_ADDR:    b'127.0.0.1'
HTTP_HOST:      bytearray(b'localhost:8000')
REQUEST_METHOD: bytearray(b'GET')
REQUEST_SCHEME: b'http'
REQUEST_URI:    bytearray(b'/hello?a=1&b=2')
PATH:           bytearray(b'/hello')
QUERY:          {'a': ['1'], 'b': ['2']}
QUERY_STRING:   bytearray(b'a=1&b=2')
VERSION:        b'1.1'
```
After:
```python
REMOTE_ADDR:    b'127.0.0.1'
HTTP_HOST:      b'localhost:8000'
REQUEST_METHOD: b'GET'
REQUEST_SCHEME: b'http'
REQUEST_URI:    b'/hello?a=1&b=2'
PATH:           b'/hello'
QUERY:          {'a': ['1'], 'b': ['2']}
QUERY_STRING:   b'a=1&b=2'
VERSION:        b'1.1'
```
> standardize header to bytes

- alltests.py
- tests/http_server.py
- tests/test_http_client.py
- tremolo/__init__.py
- tremolo/tremolo.py
'fork' mode is complex.
Changed in version 3.12: If Python is able to detect that your process has multiple threads, the [os.fork()](https://docs.python.org/3/library/os.html#os.fork) function that this start method calls internally will raise a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning). Use a different start method.
> set spawn mode as default

- tests/http_server.py
- tremolo/handlers.py
- tremolo/http_server.py
- tremolo/lib/http_protocol.py
- websocket_chat.py
Before:
```python
@app.route('/hello')
async def hello_world(request=None, response=None, **server):
pass
```
After:
```python
@app.route('/hello')
async def hello_world(request, response, **server):
pass
```
or
```python
@app.route('/hello')
async def hello_world(request, **server):
pass
```
This means that passing a `None` value is no longer required, as long as the `request` is placed first, and it may be followed by the `response`.
> make the request (and response) parameters leftmost

- tests/http_server.py
- tremolo/asgi_server.py
- tremolo/http_server.py
- tremolo/lib/http_protocol.py
- tremolo/tremolo.py
To be able to use:
```python
server['app'].create_task()
```
which is more intuitive than:
```python
server['request'].protocol.create_backround_task()
```
> refactor, expose app object to **server

- examples/upload_and_save.py
- examples/upload_and_stream.py
- tremolo/asgi_server.py
- tremolo/http_server.py
- tremolo/lib/http_protocol.py
- tremolo/utils.py
by disallowing further `send()` after an exc occurs.
> fix regression curl "leftovers after chunking" on asgi exc

- tremolo/asgi_server.py
- tremolo/lib/http_request.py
This hides a lot of ws noise that is not so important.
> don't print_exception on WebSocketClientClosed (asgi)

- tremolo/lib/http_protocol.py
Force this *tail data* to be processed by the parser (inside `data_received()`). Rather than passively waiting for next `data_received()` to be called by the transport.
> recycle the tail data in the buffer

- tremolo/lib/http_protocol.py
- tremolo/lib/http_request.py
- tremolo/lib/response.py
`request.body()` and `request.form()` should not be called after an upgraded connection,
so this should be OK and will add safety as a side effect.
> set request._body to None on upgrade

- tests/http_server.py
- tremolo/http_server.py
```python
app.routes = {
key: [],
-1: []
}
```
**Facts:** All routes you add with the `@app.route` decorator will be categorized with `key` (bytes).
```python
path = b'/my/cool/path'
parts = path.strip(b'/').split(b'/', 254)
key = bytes([len(parts)]) + parts[0]  # b'\03my'
```
When the request comes, Tremolo will also obtain keys such as `b'\03my'` from `request.path` which will be used to speed up the lookup.
In dynamic routing with regex, keys **cannot be generated at boot time** (due to its ambiguity), but can be obtained when a request arrives.
So regex routes are initially put in the key group `-1` and when the request comes, they will be (re)populated in such a way as to reduce the iteration to the entire list of `-1`.
In previous Tremolo versions, upon a successful match, the …
> rescan if pattern is not found in the routing list

- tests/http_server.py
- tests/test_http_server.py
- tremolo/__main__.py
- tremolo/http_server.py
- tremolo/lib/contexts.py
- tremolo/lib/executors.py
- tremolo/lib/http_response.py
- tremolo/lib/locks.py
- tremolo/routes.py
- tremolo/tremolo.py
- tremolo/utils.py
```python
from threading import current_thread
@app.route('/')
def sync_handler(request, **server):
return current_thread().name
```
Unlike the standard library's `ThreadPoolExecutor`, we aim to create a custom executor **that allows us to choose which thread to run on (deterministically)**. E.g. `executor.submit(func, name=THREAD_NUM)`. To support thread-sensitive objects later on.
The executor is created by reusing the [awaiter](https://github.com/nggit/awaiter) code, simplified to be more specific to Tremolo.
**Good:**
Determining `is_async` or not is *ahead of time* (compiled when the worker starts. See `Routes.compile`). It certainly saves checking thousands of times, especially when your application has many requests coming in. So supporting both `async` and sync handlers at the …
> support synchronous handlers using threads

- tests/http_server.py
- tests/middlewares.py
- tests/test_http_server.py
- tests/test_tremolo_objects.py
- tremolo/http_server.py
- tremolo/tremolo.py
Bottle's `app.mount` can be implemented without much refactoring. Behavior may differ slightly due to underlying design choices.
```python
from tremolo import Application
main = Application()
sub = Application()
subsub = Application()
@subsub.route('/hello')
async def hello_world(**server):
return 'Hello world!', 'latin-1'
sub.mount('/subsub', subsub)
main.mount('/sub', sub)
if __name__ == '__main__':
main.run('0.0.0.0', 8000, debug=True)
```
```python
app.mount('/sub', otherapp)
app.mount('/sub', otherapp)
```
> add app.mount

- tests/http_server.py
- tremolo/lib/http_request.py
- tremolo/lib/http_response.py
- tremolo/routes.py
- tremolo/utils.py
Synchronous handlers is already supported in https://github.com/nggit/tremolo/pull/286 .
But the problem is a bit awkward accessing coroutine objects like `request.form()` or `request.body()`.
As we cannot use `await` inside regular functions!
A minimal solution is to implement `AsyncToSyncWrapper` or `to_sync`. This allows calls without `await`.
```python
@app.route('/async')
async def async_handler(request, **server):
print(request)  # <tremolo.lib.http_request.HTTPRequest object at 0x...>
data = await request.body()
return data
@app.route('/sync')
def sync_handler(request, **server):
print(request)  # <tremolo.utils.AsyncToSyncWrapper object at 0x...>
data = request.body()  # it works!
return data
```
> add AsyncToSyncWrapper

- README.md
- examples/upload_and_save.py
- tea.yaml
- tremolo/lib/http_protocol.py
- tremolo/lib/http_request.py
Added the `part.stream()` method to make it simpler to use and more intuitive.
```python
async for part in request.files(max_file_size=16384):
filename = part['filename']
async for data in part.stream():
async for data in part.stream():
raise ValueError  # should not raised!
```
This change does not break the old way.
```python
async for part in request.files(max_file_size=16384):
filename = part['filename']
data = part['data']
if part['eof']:
```
See the full example: https://github.com/nggit/tremolo/blob/main/examples/upload_and_save.py
> Multipart streaming interface update

- tremolo/lib/executors.py
> Built-in types like [dict](https://docs.python.org/3/library/stdtypes.html#dict), [list](https://docs.python.org/3/library/stdtypes.html#list), and [set](https://docs.python.org/3/library/stdtypes.html#set) use internal locks to protect against concurrent modifications in ways that behave similarly to the GIL. However, Python has not historically guaranteed specific behavior for concurrent modifications to these built-in types, so this should be treated as a description of the current implementation, not a guarantee of current or future behavior.
https://docs.python.org/3/howto/free-threading-python.html#thread-safety
> ensure thread safety

- tests/http_server.py
- tests/test_http_server.py
- tests/utils.py
- tremolo/lib/http_request.py
Allow `multipart/fom-data` to be read with `request.form()`.
Files will be populated to `request.params.files` (`dict`).
This is only suitable for handling small file uploads!!! - which when streaming using `request.files()` is overkill.
> allow multipart/form-data in request.form()

- tests/http_server.py
- tests/test_http_server.py
- tests/test_tremolo_objects.py
- tremolo/handlers.py
- tremolo/http_server.py
- tremolo/routes.py
- tremolo/tremolo.py
From the beginning, Tremolo exclusively supports only `@app.route`.
`@app.get`, `@app.post`, etc. are not implemented to prevent unnecessary lines of code or redundant API/methods.
To compensate, `@app.route` now supports decorating classes as well, so you can separate methods more cleanly.
**OLD:**
```python
@app.route('/hello')
async def hello_world(request, **server):
if request.method == b'GET':
return 'Hello, World!'
if request.method == b'POST':
return await request.body()
raise MethodNotAllowed
```
**NEW:**
```python
@app.route('/hello')
class HelloWorld:
async def get(self, **server):
return 'Hello, World!'
async def post(self, request, **server):
return await request.body()
```
Any arbitrary options in `@app.route(, **options)` or `app.add_route(, **options)` will be received in …
> support decorating classes / class-based views

- tests/http_server.py
- tests/test_http_server.py
- tremolo/lib/http_request.py
[4.8](https://datatracker.ietf.org/doc/html/rfc7578#section-4.8).  Other "Content-" Header Fields
The multipart/form-data media type does not support any MIME header
fields in parts other than Content-Type, Content-Disposition, and (in
limited circumstances) Content-Transfer-Encoding.  Other header
fields MUST NOT be included and MUST be ignored.
> ignore Content-Length in multipart

- tests/http_server.py
- tests/test_http_server.py
- tremolo/asgi_server.py
- tremolo/lib/http_protocol.py
- tremolo/lib/http_request.py
- tremolo/lib/queue.py
- tremolo/lib/request.py
Connection reuse or keep-alive was previously disabled in cases of _chunked_ requests or requests without Content-Length to prevent desync.
It can now be enabled with `--experimental`, or `experimental=True` due to improved parsing.
> optimize chunked encoding parsing
