- setup.py
- tremolo/__init__.py
- tremolo/asgi_lifespan.py
- tremolo/lib/http_protocol.py
- tremolo/lib/http_response.py
This will allow partial downloading. e.g. want to avoid zeros in [sparse files](https://en.wikipedia.org/wiki/Sparse_file).
> Allow override file_size in response.sendfile

- tests/test_tremolo_objects.py
- tremolo/__init__.py
- tremolo/__main__.py
- tremolo/lib/http_protocol.py
- tremolo/lib/pools.py
- tremolo/tremolo.py
> refactor pool, add max_connections

- tests/test_h1parser.py
- tremolo/lib/h1parser/parse_header.py
- tremolo/lib/http_protocol.py
- tremolo/lib/http_request.py
used to work on python 2.7, remove that part now
> clean up parser

- tremolo/__init__.py
- tremolo/tremolo.py
> release 0.0.701

- tremolo/__init__.py
> release 0.0.710

- tremolo/__init__.py
> release 0.0.711

- tremolo/__init__.py
> release 0.0.720

- tremolo/__init__.py
> release 0.0.750

- tremolo/__init__.py
> release 0.0.751

- tremolo/__init__.py
> release 0.0.760

- tremolo/__init__.py
> release 0.0.762

- tremolo/__init__.py
> release 0.0.775

- alltests.py
- tests/test_asgi_server.py
- tests/test_http_server.py
- tremolo/managers.py
- tremolo/tremolo.py
- Split process manager into a separate file, [managers.py](tremolo/managers.py)
> refactor process manager

- tremolo/__init__.py
> release 0.0.800

- tremolo/__init__.py
> release 0.0.801

- tremolo/__init__.py
> release 0.0.803

- tremolo/__init__.py
> release 0.0.804

- tremolo/__init__.py
> release 0.0.805

- tremolo/__init__.py
> release 0.0.840

- tremolo/__init__.py
> release 0.0.850

- tremolo/__init__.py
Happy new year!
- #193 
- #192 
- #191 
- #190
> release 0.1.0

- tremolo/__init__.py
> release 0.1.1

- tremolo/__init__.py
> release 0.1.2

- tremolo/__init__.py
> release 0.1.4

- tremolo/__init__.py
- #215 
- #214 
- #213 
- #212 
- #211
> release 0.1.5

- tremolo/__init__.py
> release 0.2.0

- tremolo/__init__.py
This release fixes memory usage on keepalive.
- #222 
- #221 
- #220
> release 0.2.1

- tremolo/__init__.py
> release 0.2.2

- tremolo/__init__.py
- #230 
- #229 
- #228 
- #226
> release 0.2.3

- tremolo/__init__.py
- #236 
- #235 
- #234 
- #233 
- #232
> release 0.2.4

- tremolo/__init__.py
> release 0.2.5

- tremolo/__init__.py
> release 0.2.6

- tremolo/__init__.py
> release 0.2.7

- tremolo/__init__.py
> release 0.2.9

- tremolo/__init__.py
> release 0.2.11

- .github/workflows/tests_and_coverage.yml
- tremolo/asgi_server.py
- tremolo/http_server.py
- tremolo/lib/http_protocol.py
- tremolo/lib/http_request.py
- tremolo/lib/http_response.py
- tremolo/lib/request.py
- tremolo/lib/response.py
- tremolo/lib/websocket.py
Slightly reduces the lines of code to not create a separate dict object.
> use protocol.__dict__ as server object

- tremolo/tremolo.py
> unrestricted worker_num

- tremolo/__init__.py
- #262 
- #261 
- #260 
- #259
> release 0.3.0

- tremolo/__init__.py
> release 0.3.1

- pyproject.toml
- tremolo/__init__.py
> release 0.3.3

- examples/sse_notifications.py
working on building out a proper SSE example. The on-page notifications are working but I've noticed a few issues with forms.
1. A "regular" form (one that doesn't have any content-type header or enctype set) throws an error when processed by request.form()
2. When preventing the standard form submission, the FormData object is not being parsed correctly as a dictionary of key-value pairs.
Any simple answers that I'm missing?
> Live Notifications with SSE

- tremolo/tremolo.py
Before (`**kwargs` is a must):
```python
app = Application()
@app.on_worker_start
async def worker_start(app, **kwargs):
pass
```
Now supports to only pass a single `app`:
```python
@app.on_worker_start
async def worker_start(app):
pass
```
For those wondering if the `app` outside and `app` inside function are the same: Yes, it is the same type. But is a completely different instance that is in a different process. No longer in main.
To avoid pickling issues, especially for complex objects, as much as possible define those objects inside the function rather than outside. You can use `app.context` (inside) to store your objects for global sharing.
> allow single parameter 'app' in worker hooks

- tremolo/__init__.py
> release 0.4.1

- tremolo/__init__.py
- #303 
- #302 
- #300 
- #298 
- #297
> release 0.4.2
